name: Continuous Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    uses: myfin-tracker/application/.github/workflows/application-deployment.yml@main
    with:
      DEPLOYMENT_HOST_SSH_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_HOST_SSH_PRIVATE_KEY }}
      DEPLOYMENT_HOST_IP: ${{ secrets.DEPLOYMENT_HOST_IP }}
      DEPLOYMENT_HOST_USERNAME: ${{ secrets.DEPLOYMENT_HOST_USERNAME }}
